a = int(input("enter first number"))
print(a)
b = int(input("enter second number"))
print(b)
c = int(input("enter third number"))
print(c)
print("average of three numbers is=", (int(a) + int(b) + int(c) / 3))
